// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PersonalFIT - Treino Inteligente e Personalizado",
  description: "Treinos personalizados com inteligência artificial. O teu personal trainer disponível 24/7 para te ajudar a alcançar os teus objetivos de fitness.",
  keywords: ["PersonalFIT", "Personal Trainer IA", "treino inteligente", "app de fitness com IA", "treino personalizado", "fitness"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="dark">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Previne tentativas automáticas de conexão ao MetaMask
              if (typeof window !== 'undefined') {
                window.addEventListener('load', function() {
                  if (window.ethereum) {
                    window.ethereum.autoRefreshOnNetworkChange = false;
                  }
                });
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}